### ISSUE TITLE
PythonAPI seems to not parse polaritonic parameters properly

### ISSUE THREAD

**Issue by BauerMarco** [edeprince3/hilbert#32]
Hi Eugene,

Could you do me a favor and double check, whether the processing of a polaritonic SCF calculation using python instead of the psi4 executable yields the correct result? For me it doesn't, but the calculation runs through, so either I am experiencing a weird bug, which might have introduced itself during installation, or executing the calculation using python does not parse either the coupling or frequency parameters or both incorrectly. This is what I would guess from my observations, since with varying parameters I always obtain the uncoupled result. Everything works fine with the psi4 executable though (successful test runs, etc.).

**Comment by edeprince3** [comment]
Sure, can you give me the python code that doesn't work?

**Comment by edeprince3** [comment]
this seems to work (it gives the same result as tests/qed_ccsd/input.dat):

import psi4
import hilbert
import numpy as np

def main():

    mol = psi4.geometry("""
    0 1
         O            0.000000000000     0.000000000000    -0.068516219320
         H            0.000000000000    -0.790689573744     0.543701060715
         H            0.000000000000     0.790689573744     0.543701060715
    symmetry c1
    """)

    psi4.set_options({
      'basis':           'cc-pvdz',
      'scf_type':        'df',
      'd_convergence':   1e-12,
      'e_convergence':   1e-12,
    })

    # frequency: 2.0 eV
    w = 0.07349864501573
    
    # lambda: 0.05
    # coupling g = 0.05 / sqrt(2*w)
    g = 0.05 / np.sqrt(2.0 * w)

    psi4.set_module_options('hilbert', {
        'maxiter':                   500,
        'cavity_frequency':          [0.0, 0.0, w],
        'cavity_coupling_strength':  [0.0, 0.0, g],
        'polaritonic_cc_include_u0': True,
        'polaritonic_cc_include_u1': True,
        'polaritonic_cc_include_u2': True,
        'r_convergence':             1e-12
    })

    psi4.activate(mol)

    # get scf wfn
    scf_energy,ref_wfn = psi4.energy('scf',return_wfn=True)

    # grab options object
    options = psi4.core.get_options()
    options.set_current_module('HILBERT')

    energy = psi4.energy('qed-ccsd')
    return energy, mol.nuclear_repulsion_energy()

if __name__ == "__main__":
    main()

**Comment by BauerMarco** [comment]
I tried your example, and I still obtain the same energies when varying either the photon energy or the coupling strength or both.

At least that means, that the error is not in the hilbert package, but in how I set it up.

Thank you!
